ansible-container:
  # If no $DOCKER_HOST then we need to run privileged so we can access /var/run/docker.sock
  {% if not env.DOCKER_HOST %}privileged: true{% endif %}
  image: "{{ builder_img_id }}"
  command: /usr/local/bin/builder.sh /usr/local/bin/ansible-playbook -i /etc/ansible/ansible-container-inventory.py -c docker {{ params.ansible_options | join(' ')  }} --list-hosts {% if params.playbook %} /tmp/playbooks/{{ params.playbook.split('/')[-1] }} {% else %} main.yml {% endif %}
  environment:
    {% if env.DOCKER_HOST %}- DOCKER_HOST{% else %}- DOCKER_HOST=unix:///var/run/docker.sock{% endif %}
    {% if env.DOCKER_TLS_VERIFY %}- DOCKER_TLS_VERIFY{% endif %}
    {% if env.DOCKER_CERT_PATH %}- DOCKER_CERT_PATH=/docker-certs/{% endif %}
    - COMPOSE_HTTP_TIMEOUT=3000
    - DOCKER_API_VERSION={{ api_version }}
    - ANSIBLE_ORCHESTRATED_HOSTS={% for host in hosts %}{{ host }}{% if not loop.last %},{% endif %}{% endfor %}
  volumes:
    {% if not env.DOCKER_HOST %}- /var/run/docker.sock:/var/run/docker.sock{% endif %}
    {% if env.DOCKER_CERT_PATH %}- $DOCKER_CERT_PATH:/docker-certs/:Z{% endif %}
    {% if params.playbook %}- {{ params.playbook }}:/tmp/playbooks/{{ params.playbook.split('/')[-1] }}:Z {% endif %}
    - {{ base_path }}:/ansible-container/:Z

  working_dir: /ansible-container/ansible/
  stdin_open: true
  tty: true
{{ config }}
