from: ubuntu:trusty
environment:
  APACHE_PORT: '{{ apache_port }}'
labels:
# Single label
  a: '1'
# Multiple labels
  b: '2'
# Multiple labels
  c: '3'
# Quoted keys and values
  the bird: the word
# Multi-line
  foo: bar
  baz: buzz
# I am metadata
command:
- /usr/sbin/apache2
- -DFOREGROUND
entrypoint:
- /usr/sbin/dumb-init
ports:
- '{{ apache_port }}'
user: www-data
volumes:
- /vol
working_dir: /tmp
shell:
- /bin/sh
- -c
