version: "1"
services:
  # Add your containers here, specifying the base image you want to build from
  # For example:
  web:
    image: nginx
    ports:
      - "80:80"
    environment:
      - NGINX_PORT=80
